Repository AM1CODES/Poke-Dex, pull requests merged in 2020-10, with the labels that each got.

#48 Update index.html
  index.html
Labels: Hacktoberfest

#47 Added my favourite pokemon
  index.html
Labels: Hacktoberfest

#46 added jolteon
  index.html
Labels: Hacktoberfest

#44 Added a card of Mewtwo with description and my name
  index.html
Labels: Hacktoberfest

#43 Added new Pokémon
  index.html
Labels: Hacktoberfest

#42 Added darkrai to pokedex
  index.html
Labels: Hacktoberfest

#49 Added gyarados
  index.html
Labels: Hacktoberfest

#40 Added a new pokemon
  README.md
  index.html
Labels: Hacktoberfest

#39 added gyarados
  .idea/Poke-Dex.iml
  index.html
Labels: Hacktoberfest

#38 Add a new Pokemon - Togepi
  index.html
Labels: Hacktoberfest

#36 correct indentation and add greninja
  index.html
Labels: Hacktoberfest

#50 Update index.html
  index.html
Labels: Hacktoberfest

#34 Added Dialga!
  index.html
Labels: Hacktoberfest

#33 added card for raichu
  index.html
Labels: Hacktoberfest

#31 Added 3 pokemon
  index.html
Labels: Hacktoberfest

#29 added Magikarp
  index.html
Labels: Hacktoberfest

#28 Add Ditto
  index.html
Labels: Hacktoberfest

#27 updated snorlax
  index.html
Labels: Hacktoberfest

#51 Add Squirtle
  index.html
Labels: Hacktoberfest

#52 Added Cyndaquil
  index.html
Labels: Hacktoberfest

#59 Added finally my pokemon .
  asd
  index.html
Labels: Hacktoberfest

#60 Updated index.html
  index.html
Labels: Hacktoberfest

#61 Croagunk added to Pokedex
  index.html
Labels: Hacktoberfest

#57 added psyduck in index.html
  index.html
Labels: Hacktoberfest

#54 Spelling correction in README.md
  README.md
Labels: Hacktoberfest

#53 Added Charmander
  index.html
Labels: Hacktoberfest

#62 [add] my favorite pokemon Jolteon
  index.html
Labels: Hacktoberfest

#63 Added Onix to pokedex, and removed excess angular bracket
  about.html
  index.html
Labels: Hacktoberfest

#65 add Charmander
  index.html
Labels: Hacktoberfest

#66 Add Snorlax
  index.html
Labels: Hacktoberfest

#68 added ground pokemon
  index.html
Labels: Hacktoberfest

#69 Add Munchlax
  index.html
Labels: Hacktoberfest

#72 Added a new pokemon Hoopa Unbound
  index.html
Labels: Hacktoberfest

#76 Add pokemon card
  index.html
Labels: Hacktoberfest

#75 add card pokemon riolu by nikhil omkar
  index.html
Labels: Hacktoberfest

#77 Added 2 pokemons to the webpage
  images/pachirisu.png
  images/solgaleo.jpg
  index.html
Labels: Hacktoberfest

#79 Added favorite Pokémon, Slaking and filled in alt attributes for image elements
  index.html
Labels: Hacktoberfest

#86 Added Mudkip
  index.html
Labels: Hacktoberfest

#87 added Scizor to the pokedex
  index.html
Labels: Hacktoberfest

#88 Added new pokemon, Infernape
  index.html
Labels: Hacktoberfest

#94 Added Wailord
  index.html
Labels: Hacktoberfest

#95 added pokemon
  index.html
Labels: Hacktoberfest

#99 Added Giratina
  images/giratina.png
  index.html
Labels: Hacktoberfest

#195 Leafeon
  images/leaf.png
  index.html
Labels: hacktoberfest - accepted

#197 Add kyogre to the pokedex + update .gitignore to ignore .idea files
  .gitignore
  index.html
Labels: hacktoberfest - accepted

#205 added Weavile to the pokedex
  index.html
Labels: hacktoberfest - accepted

#228 Added Aurorus to the poke dex
  index.html
Labels: hacktoberfest - accepted

#186 Added Fletchinder pokemon
  about.html
  index.html
Labels: bug

#237 added palkia
  index.html
Labels: hacktoberfest - accepted

#266 added a few more pokémons
  index.html
Labels: hacktoberfest - accepted

#280 Added the Leafeon card to the Pokedex, aka the index.html
  index.html
Labels: hacktoberfest - accepted

#288 Add Wobbuffet
  index.html
Labels: hacktoberfest - accepted

#286 4-pokemon update
  index.html
Labels: bug, hacktoberfest - accepted

#341 Removed and fixed my pokemon code
  index.html
Labels: hacktoberfest - accepted

#361 Added Ducklet
  index.html
Labels: hacktoberfest - accepted

#364 Added Pokemon Genesect
  index.html
Labels: hacktoberfest - accepted

#388 Added Latios
  index.html
Labels: hacktoberfest - accepted
