Repository AM1CODES/Poke-Dex, pull requests merged in 2021-10, with the labels that each got.

#499 Update index.html
  index.html
Labels: hacktoberfest-accepted

#501 feat: replace broken images with a fallback image
  images/fallback_image.png
  index.js
Labels: hacktoberfest-accepted

#502 feat: add rowlet
  images/rowlet.png
  index.html
Labels: hacktoberfest-accepted

#503 added Wurmple pokemon
  index.html
Labels: hacktoberfest-accepted

#504 Added Togetic
  index.html
Labels: hacktoberfest-accepted

#505 Added Metagross (Pokedex number #376)
  index.html
Labels: hacktoberfest-accepted

#516 Fixed image rendering issues of many pokemons
  index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#524 Added my favorite pokemon- Cresselia
  index.html
Labels: hacktoberfest-accepted

#509 Added new Pokemon Gible
  images/gible.png
  index.html
Labels: hacktoberfest-accepted

#507 Added my fav pokemon
  index.html
Labels: hacktoberfest-accepted

#508 Added Carbink from generation 4
  .DS_Store
  .gitignore
  .idea/Poke-Dex.iml
  CONTRIBUTING.md
  Poke-Dex
  README.md
  about.css
  about.html
  asd
  git
  icons/favicon.ico
  icons/grid-large.png
  icons/grid-small.png
  icons/pokeball.png
  icons/pokedex.svg
  images/1200px-243Raikou.webp
  images/Carbink.png
  images/Dragonite.png
  images/Escavalier.png
  images/Hawlucha.png
  images/Lugia.png
  images/Plusle.png
  images/Pokedex_icon-icons.com_67530.svg
  images/abra.jpg
  images/added Rayquaza
  images/arceus.png
  images/butterfree.png
  images/castform.jpg
  images/fallback_image.png
  images/gengar.png
  images/giratina.png
  images/leaf.png
  images/magicarp.jpg
  images/marshadow.png
  images/meowth.png
  images/pachirisu.png
  images/pichu.png
  images/poliwag.jpg
  images/porygon.jpg
  images/regigigas.jpg
  images/rowlet.png
  images/seaking.jpg
  images/shuckle.webp
  images/solgaleo.jpg
  images/wartortle.png
  images/zapdos.png
  index.css
  index.html
  index.js
  package-lock.json
  pokemon_god.html
Labels: Hacktoberfest, Creative, hacktoberfest-accepted
